title: Lokete 
iconURL: assets/default-icon.png
remote_theme: SupunKavinda/jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: 
  github: Iokete

plugins:
 - jekyll-feed
 - jekyll-seo-tag

exclude:
  - _sass
  - .github
  - _includes/_includes/hyvor-talk-comments.html
  - _layouts
  - .github 
  - LICENSE.txt
  - screenshot.png
  - README.md
  - .gitignore
  - vendor
  

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
